// NOTE: this file is auto-generated by Construct
declare class IConstructProjectGlobalVariables {
	Dialogue_IsRunning: boolean;
	Dialogue_WaitForInput: number;
	Dialogue_WaitForChoice: number;
	Dialogue_TapChoice: number;
	GameType: string;
	BehaviorInstanceUid: number;
	Camera_Z: number;
	Camera_Y_Offest: number;
	Camera_X_Offest: number;
	Camera_Angel: number;
	Camera_Angel_De: number;
	Camera_Z_De: number;
	Camera_Y_Offest_De: number;
	Camera_X_Offest_De: number;
	temp: string;
	Function_WindowID: number;
	Function_ID: number;
	Function_WindowEnable: boolean;
	Function_OPT_Count: number;
	Fade_is_Fading: boolean;
	End_TriggerEnd: boolean;
	End_Des_Text1: string;
	End_Des_Text2: string;
	End_Des_Text3: string;
	End_Des_Text4: string;
	Load_is_LoadingState: boolean;
}