// NOTE: this file is auto-generated by Construct
declare namespace InstanceType {
	class Browser extends IInstance {
	}
	class Audio extends IInstance {
	}
	class AJAX extends IInstance {
	}
	class DialogueCommands extends IDictionaryInstance {
	}
	class DialogueData extends IArrayInstance {
	}
	class DialogueDictionary extends IDictionaryInstance {
	}
	class GameVariables extends IDictionaryInstance {
	}
	class Touch extends IInstance {
	}
	class ChoiceSelector extends IWorldInstance {
		instVars: {
			callback: string,
			params: string
		};
	}
	class ContinueIndicator extends ISpriteInstance {
	}
	class __doorBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class door extends IWorldInstance {
		behaviors: __doorBehaviors<this>;
	}
	class DownArrow extends ISpriteInstance {
	}
	class PortraitSprite extends ISpriteInstance {
	}
	class SpriteFont extends ISpriteFontInstance {
		instVars: {
			ID: string,
			choiceFork: string
		};
	}
	class UpArrow extends ISpriteInstance {
	}
	class WindowFrame extends IWorldInstance {
		instVars: {
			ID: string
		};
	}
	class FuntionWinodow9 extends IWorldInstance {
		instVars: {
			ID: string
		};
	}
	class ground extends ITiledBackgroundInstance {
	}
	class __wallBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class wall extends I3DShapeInstance {
		behaviors: __wallBehaviors<this>;
	}
	class __prisonerMainBehaviors<InstType> {
		"8Direction": I8DirectionBehaviorInstance<InstType>;
		车: ICarBehaviorInstance<InstType>;
	}
	class prisonerMain extends ISpriteInstance {
		behaviors: __prisonerMainBehaviors<this>;
	}
	class prisoner3dobject extends IWorldInstance {
	}
	class CameraMain extends IInstance {
	}
	class Keyboard extends IInstance {
	}
	class __bedBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class bed extends IWorldInstance {
		behaviors: __bedBehaviors<this>;
	}
	class __guardBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class guard extends IWorldInstance {
		behaviors: __guardBehaviors<this>;
	}
	class __toiletBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class toilet extends IWorldInstance {
		behaviors: __toiletBehaviors<this>;
	}
	class __washBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class wash extends IWorldInstance {
		behaviors: __washBehaviors<this>;
	}
	class IntractBehaviorZone extends ISpriteInstance {
		instVars: {
			isTouceOnce: boolean,
			TouceTimes: number,
			Type: string,
			DialogueKeyName: string,
			functionName: string,
			isConnectNPC: boolean,
			NPCUid: number,
			isTouching: boolean,
			DistancefromPlayer: number,
			parameters1: string,
			parameters2: string,
			parameters3: string,
			parameters4: string,
			parameters5: string
		};
	}
	class EventHandler extends ISpriteInstance {
	}
	class board extends IWorldInstance {
	}
	class __camera_coverBehaviors<InstType> {
		Orbit: IOrbitBehaviorInstance<InstType>;
		Pin: IBehaviorInstance<InstType>;
	}
	class camera_cover extends ISpriteInstance {
		behaviors: __camera_coverBehaviors<this>;
	}
	class guardbutfake extends IWorldInstance {
	}
	class FunctionWindow extends ISpriteInstance {
		instVars: {
			id: number
		};
	}
	class FunctionOPT extends ITextInstance {
		instVars: {
			id: number,
			name: string,
			isSelected: boolean,
			isEnable: boolean
		};
	}
	class __FadeSpriteBehaviors<InstType> {
		Fading: IFadeBehaviorInstance<InstType>;
	}
	class FadeSprite extends ISpriteInstance {
		behaviors: __FadeSpriteBehaviors<this>;
	}
	class TouchBehaviorZone extends ISpriteInstance {
		instVars: {
			isTouchOnce: boolean,
			Type: string,
			FunctionName: string,
			ID: number,
			TouchTimes: number,
			isTestOverLapDoing: boolean
		};
	}
	class Strawground extends IWorldInstance {
	}
	class Object3D extends IWorldInstance {
	}
	class Suitcase extends IWorldInstance {
	}
	class __TunnelentranceBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class Tunnelentrance extends IWorldInstance {
		behaviors: __TunnelentranceBehaviors<this>;
	}
	class Airvents extends IWorldInstance {
	}
	class American extends IWorldInstance {
	}
	class NudePolice extends IWorldInstance {
	}
	class Prisonerother extends IWorldInstance {
	}
	class EndingBackGround extends ISpriteInstance {
	}
	class EndTitle extends ITextInstance {
	}
	class __AnykeyBehaviors<InstType> {
		正弦运动: ISineBehaviorInstance<InstType>;
	}
	class Anykey extends ITextInstance {
		behaviors: __AnykeyBehaviors<this>;
	}
	class MenuBackground extends ISpriteInstance {
	}
	class __f_cubeBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class f_cube extends I3DShapeInstance {
		behaviors: __f_cubeBehaviors<this>;
	}
	class __f_cube2Behaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class f_cube2 extends IWorldInstance {
		behaviors: __f_cube2Behaviors<this>;
	}
	class f_3d extends IWorldInstance {
	}

}